### ISSUE TITLE
Useful and/or Fun uses of HRORM

### ISSUE THREAD

**Issue by kazetsukaimiko** [ojplg/hrorm#11]
Testing and refinement are themes that keep coming up, I think it would be nice to have something that kind of showcases and really puts this library to the test. 

I've been using HRORM for a work-related project that I cannot share alot of details about. Especially as of the 0.7.0 release, this covers really all of my needs there.

I was thinking of banging out an Undertow / CDI / JAX-RS app of some sort to show off how simple this is to integrate. Ideally it would allow for Keyed, Keyless, and Join operations internally.

My current idea is an app to keep track of local media. Indexing, thumbnailing, FTS, the usual stuff plus streaming and whatnot. Usually, my go-to database stack is NitriteDB (https://www.dizitart.org/nitrite-database/) , but I could try to implement something using H2 and HRORM.

I'm fairly confident I'll run into problems of some sort along the way, in which I'll have concrete use cases to demonstrate actual issues and pain points. I'm interested in whether you think this may help you, I think there's some room for mutual benefit here.

I think it would be great if I could give the user a choice of common SQL databases without the annoyances of setting up the typical JPA stacks. Some potential features that already came to mind when thinking of spinning up a new stack was the ability for Daos to drop, empty, and create tables.

**Comment by ojplg** [comment]
Writing a demo application using hrorm would be super cool.

Hrorm was originally created when I was writing an application called legup (also on github), but legup is not very friendly to look at. It has a lot of junk in it that has nothing to do with persisting data.

I thought about adding functions to hrorm for creating schema, but I did not need it, so I didn't. I think it would be great to have it.

I never consider dropping and emptying, but sure, those are important too.

I would not add those to the Dao interface though. I would create a new interface (SchemaAdminstration or something) that is completely independent. I would not want a Dao (which is something that should be exposed to the application generally) to have access to ability to start wiping out tables. That's asking for a catastrophic bug.

And yeah, anything that you run into that hrorm doesn't do, you should open it up for discussion.

The docs are really out of date now. There are a bunch of places where it says hrorm requires keys, and that just is not true any more.

**Comment by kazetsukaimiko** [comment]
About halfway through a chat app, the service layer has so far gone smoothly, but yeah, so far:

1. Wishing I had that ensureTableExists() method. 
2. selectAll() could be selectAll(Modifier...) for rear-end modifiers like ORDER BY x DESC.

I'm also building a parallel service layer with Nitrite, and might do one for Mongo or JPA as well, to express the differences in implementations.

As soon as something runs, I'll put the source up.

**Comment by ojplg** [comment]
The Validator class should check if the table exists.

Yeah, ordering is not something hrorm has at the moment. Other than ordering, what other modifiers are there?

**Comment by kazetsukaimiko** [comment]
I was thinking Limit, but for instance SQL Server uses:

`SELECT TOP 10 * FROM TABLE WHERE 1=1`
Whereas Oracle:
`SELECT * FROM TABLE WHERE 1=1 LIMIT 10`

This is already turning out to be a fruitful exercise. Something I just ran into:
```
    @Override
    public List<Message> getMessagesOfRoom(Room room) {
        // dao.select(where("room", Operator.EQUALS, room)); // Not possible!
        return dao.selectAll() // Workaround
                .stream()
                .filter(message -> Objects.equals(room, message.getRoom()))
                .collect(Collectors.toList());
    }
```

About to push to:
https://github.com/kazetsukaimiko/hrormchat

I gave up on non-Long keys for the time being, but will have room for it later.

**Update: I did push.** Here's the entities I'm going for at the moment:
https://github.com/kazetsukaimiko/hrormchat/tree/master/hrormchat-api/src/main/java/io/freedriver/hrormchat/entity

**Comment by ojplg** [comment]
Yeah, that's a pretty serious miss! (I mean the select where joined item is X thing.)

I was just concentrating on one table. I don't think it should be so hard to implement, but I really have not thought about it.

**Comment by ojplg** [comment]
So, there are two ways to do what you want.

1. Use a template object. Works pretty well in this case.
```
Message msgTemplate = new Message();
msgTemplate.setRoom(room);
List<Message> messages = messageDao.selectManyByColumns(msgTemplate, "roomId");
```

2. Use a where clause on the room ID.
```
List<Message> messages = messageDao.select(where("roomId", EQUALS, room.getId());
```

Those will generate virtually identical SQL.

It's a shame that in both cases you need to talk about roomIds, but I cannot think of any way to avoid that.

Another issue that comes to mind is whether messages should be siblings or children of rooms.

It's possible that messages should be children of BOTH rooms and authors. What does hrorm do with that? I cannot remember.

**Comment by ojplg** [comment]
Hrorm supports exactly one or zero parent class per child class. Perhaps things should be allowed two or more parents? Not sure.

**Comment by kazetsukaimiko** [comment]
> Yeah, that's a pretty serious miss! (I mean the select where joined item is X thing.)
> 

Don't be too hard on yourself about it, but if you allow the user to specify a column representing an entity that is to be joined. expect this to come up.

> ```
> List<Message> messages = messageDao.select(where("roomId", EQUALS, room.getId());
> ```
> 

This is a good workaround, and I think acceptable as the "go to" for the use case. I think better than the previous, anyway. 

This makes me think that DaoBuilder isn't enough on its own to conceptually describe what the user wants. You probably need something representing the datasource (all tables), and something else representing your entity graph, then a mapping between datasource and the entity graph. There's nothing preventing someone from handing one DaoBuilder another from an entirely different datasource and claiming it is a join, for instance.

That's big, though. The solution is neat and small.

> It's a shame that in both cases you need to talk about roomIds, but I cannot think of any way to avoid that.
> 

Make the user specify the getter on the Room field to do the join on when they build the parent DaoBuilder? Or look up the PK field on the child? I think there's a way to do this for the user at fairly little cost, but I could be wrong.

> Another issue that comes to mind is whether messages should be siblings or children of rooms.
> It's possible that messages should be children of BOTH rooms and authors. What does hrorm do with that? I cannot remember.

I wouldn't model the entity layer this way unless the assumption was that this was done lazily.  What if there are bidirectional relationships in every direction? Rooms->Users, Messages, Users->Messages, Rooms, Messages->User, Room? How deep are you going to pre-load everything? 

Lazy fields are a nice feature for consuming a database. You could avoid doing joins altogether- just prepare queries instead. That would even let you hand one daobuilder another from a completely different datasource and load data that way, because there is no underlying join. That's not what you're going for however, and there are other ways to accomplish the same thing.

Eliminating all problems or fuglies isn't realistic. Querying rooms by roomId is realistic. Perhaps there are larger efforts worth undertaking. Let me keep fleshing this out, hopefully a nice balance can be struck.

**Comment by ojplg** [comment]
Order by clauses are now in hrorm. Check out release 0.7.2.

**Comment by ojplg** [comment]
Selecting with a limit should be pretty easy, if you think it's a good feature. I'm not sure.

You don't have to put the limit into the SQL, which has syntax challenges, as you note. You just iterate through the result set only as far as your limit allows.

**Comment by ojplg** [comment]
House-cleaning. Closing this issue. It seems like all the issues here were addressed. Please open a new ticket if you do still have a problem. Or if you have a new issue, of course.
