### ISSUE TITLE
Wrong column names results in NPE upon select in 0.6.0

### ISSUE THREAD

**Issue by kazetsukaimiko** [ojplg/hrorm#12]
I haven't been able to migrate from 0.6.0 yet in one of my use cases because deploying dependency JARs is kinda tricky in that environment. I ran into an issue where I had a column defined as:
"some_id"
and tried to query it using:
"someId"

This is user error, of course, but there's no validation here. Just an NPE when attempting to invoke the setter in foldingSelect.

If this issue cannot be reproduced in 0.7.x, feel free to close. I've been very busy trying to finish something up and ran into this issue along the way. I also ran into an NPE where in cases your entity field was a primitive (long) and your column is empty in the database during auto-unboxing, but that appears to be resolved in 0.7.x. ( I tried to write a test confirming this ).

If I can reproduce on 0.7.x in a test I'll submit a PR with the test so that you know where to throw an exception.

**Comment by ojplg** [comment]
I think you're saying this should result in a HrormException, not a null pointer? Something exceptional has to happen, if I understand your problem.

When you have time, providing a test case is good. I bet there are a lot of these, now that I think of it. I've never made any effort to test for this condition.

I hope being busy is suiting you well. If you ever feel like it, and it isn't giving up your business secrets, I'd love to hear about how you're using hrorm.

**Comment by kazetsukaimiko** [comment]
See my https://github.com/kazetsukaimiko/hrorm/tree/mischief-tests branch for some of the 0.6.x concerns largely addressed already in 0.7.2. The only place I think could be improved upon would be to throw more dedicated exceptions, either earlier (preferably in some validation phase) or at query time by inspecting the exception message content (Column Not Found and Data Conversion exceptions).

To see what I'm talking about, comment out the (expected = HrormException.class) part of the @Test line.

If you run the same test class under the 0.6.0 series you'll see why it was bad enough to warrant opening this issue.

**Comment by ojplg** [comment]
I merged your code into master. All the tests are still passing in master, even though hrorm is now on to release 0.7.4.

I think better than having a bunch of different types might be to have some enumeration or problems, and return a list of problems found. That's kind of how the validators work. Though that just returns strings, which is probably enough, come to think of it.

These kind of things, though they happen at runtime, are really just programming errors. The problems are generally pretty clear, you fix them once, the problem goes away.

**Comment by ojplg** [comment]
Closing this ticket. Obviously, please report any new problems or regressions you encounter.
