### ISSUE TITLE
Idea: Constructor Support

### ISSUE THREAD

**Issue by kazetsukaimiko** [ojplg/hrorm#14]
So... I ran into a "keyless join" scenario. I don't think adding joins to keyless is a great solution, however. 

The use case:
Lets say you have two different databases with different data points about the same Things. Thing in database one has ID 1. In database two, its XYZ. But there's no Thing table (it wouldn't be very useful), just a list of events about what Thing did/said/heard. What if I need to map 
1 -> XYZ?

What if I'd like to populate some of my POJO fields using REST calls, other libraries, or databases?

I've been thinking for a while about how to cleanup alot of the code, and the common theme is always to separate database concerns from POJO concerns. Its always major work, but I think I have a bite-sized solution to this one that's a step in that direction.

I think we should make the ResultSet -> POJO conversion process into an interface that can be overridden at Dao creation/build time. ResultSet has state however, so I think ideally we have a generic EntityFieldMap we build per-row from ResultSet and pass to this POJO converter interface class.

Your existing conversion code / field population logic then becomes an implementation of this interface, one the user can extend and override.

Pseudocode:
```
KeylessDao<MyEntity> dao = new IndirectKeylessDaoBuilder<>("my_entity", (entityFieldMap) -> new MyEntity(entityFieldMap), e->e)

// or
KeylessDao<MyEntity> dao = new IndirectKeylessDaoBuilder<>("my_entity", new MyExtensionOfYourPOJOBuilderClass(), e->e)

```
This will allow the user to put resources (database connections, other daos, libraries, scripting, etc) in scope during the POJO construction.

**Comment by ojplg** [comment]
I have thought about the issue of separating the object population work from the querying work, and I agree, it's potentially useful. I was thinking more in terms of allowing the user to inject SQL into Hrorm (in case you need to run some custom query that Hrorm will not support, an IN-clause to pick one example) and still take advantage of the ability to construct the objects from a result set. I never thought about using Hrorm to populate from any other source though.

Here's the issue I thought of that made it seem messy to me. When Hrorm does joins it uses prefixes to distinguish columns in result sets. So when asking for the FOO column, Hrorm actually generates SQL that names that AFOO or BFOO or CFOO, depending on the join. In fact, there's a limit to the number of joins Hrorm can do: 25 (a for the first table, b-z for the joined).

I'm not sure what the implications are for things with child entities attached. But that's not obvious either.

Are you thinking about this for Keyless entities, or all entities? For Keyless things with no children, it will be much easier.

**Comment by ojplg** [comment]
Closing this. If you still have an interest in this, and have a more concrete request or proposal, let me know.

Thanks.
