### ISSUE TITLE
Count function

### ISSUE THREAD

**Issue by kazetsukaimiko** [ojplg/hrorm#9]
foldingSelect can produce a count, but it still requires reading the full dataset, and only allows queries using equivalence, not the date ranges needed. The volumes we're working with would make it unusable regardless.

Even if not dealing with huge numbers in one table, the way HRORM does joins could balloon the dataset that way as well, this is an area where one could get themselves in trouble. An easy OutOfMemoryError was a primary motivator for the streaming work I submitted earlier.

This is to request a couple of methods on the KeylessDao interface that returns a Long count, representing the number of rows selected.

Long countByColumns(ENTITY item, Map<String, Operator> columnNames);
and
Long fullCount();

If you have no problem with these I'll submit a PR shortly with the work to hook it all up.

**Comment by kazetsukaimiko** [comment]
Just went over the diff of our count branches.

Okay, so runFunction is indeed a simpler, more versatile way of accomplishing the task. 

The part I don't like should be fairly obvious, runFunction returns java.lang.Object. I'm sure there's good rationale for it, but even if it makes sense internally, exposing that Object return on the interface to the implementer doesn't feel all warm and fuzzy on the inside.

If its unavoidable or wins the implementer something significant, I guess I'm not really opposed to it. If we're always expecting a number (all of the "functions" seem to be numeric) and don't know what type is going to come back, return the one with the highest resolution (probably BigDecimal) and then make the user cast/convert from number-to-number instead, would be my advice there.

**Comment by ojplg** [comment]
Another approach is to have a family of methods: runLongFunction, runBigDecimalFunction, and others as they become necessary. I was not sure when I made my changes. It's probably better to have the correct types, as you point out.

Even better would be to somehow intuit the response object from the type of the column. (I remember your point about wishing the columns carried their own type.) But I cannot think of any good way to do that at the moment.

If this stuff looks helpful, we can nail it down and release before we continue work on the where clauses. Let me know if that's helpful to you.

**Comment by kazetsukaimiko** [comment]
> Another approach is to have a family of methods: runLongFunction, runBigDecimalFunction, and others as they become necessary. I was not sure when I made my changes. It's probably better to have the correct types, as you point out.
> 
A compromise would be to take another parameter:
```
<NT extends Number> 
Class<NT> numericType
```
Then to choose which getTYPE on resultSet to invoke with a big if instanceof Long, else if Integer, else if Short, else if BigDecimal... and return NT.  

> Even better would be to somehow intuit the response object from the type of the column. (I remember your point about wishing the columns carried their own type.) But I cannot think of any good way to do that at the moment.
> 
I think the deep-dive is a better place to solve that. I also concluded in some of my exploratory work that it would be good to have three separate concepts:
```
Coordinate // Something you can get from an Object.
Column // A named column on a database table
Field // A mapping between Column and Coordinate.
```

> If this stuff looks helpful, we can nail it down and release before we continue work on the where clauses. Let me know if that's helpful to you.

This stuff definitely is helpful, and without rocking the boat too much. I appreciate the willingness to move forward on this even if we end up coming back and reworking some of it later.

**Comment by ojplg** [comment]
I updated my branch with a Long function and a BigDecimal function, and it seems to be working.

The methods now return null when there are no results. That seems much better than throwing an exception or returning some sentinel value, which really only works for count.

If that works for you, I will cut a release, and we can return to thinking about the bigger ticket issues.

**Comment by kazetsukaimiko** [comment]
> If that works for you, I will cut a release, and we can return to thinking about the bigger ticket issues.

Just went over the branch. Functionally, it looks good. I am a bit surprised- I would have thought you'd have preferred simpler count methods on the interface, even if you had the more versatile function methods underneath the hood.

I'm fine with what's in your branch if you want to cut.

**Comment by ojplg** [comment]
Hrorm 0.6.2 has been publicly released with support for COUNT, MIN, MAX, SUM, and AVG functions.
